[Interface]
PrivateKey = mHQmH9e9Wlaof+vck+odoS+hVBgbpQSKVrpm41y6Skk=
Address = 10.66.66.3/32,fd42:42:42::3/128
DNS = 1.1.1.1,1.0.0.1

# Uncomment the next line to set a custom MTU
# This might impact performance, so use it only if you know what you are doing
# See https://github.com/nitred/nr-wg-mtu-finder to find your optimal MTU
# MTU = 1420

[Peer]
PublicKey = EIUK+Zm+PhcETDfAH87gbjH9rTIVqodKfZT+aTX63iQ=
PresharedKey = 9ufX8PW7vab5+h86tH+3tPg6oTrjwH2yCZnfxJaJGFI=
Endpoint = 192.168.0.10:993
AllowedIPs = 0.0.0.0/0,::/0
